/* =========================================================
   PRODUCTOS DEL CATÁLOGO
   ---------------------------------------------------------
   Para sumar un producto, copiá una línea y cambiá los datos.
   Lo único obligatorio es:  nombre, categoria y precio.

   categoria:  lavado | descontaminado | pulido | proteccion |
               llantas | vidrios | interior | motor | accesorios
   precio:     número sin puntos ni signo ($13.900 -> 13900)

   Opcionales:
   tamano:      "500 ml", "1 L", "1 u"...
   descripcion: texto corto de venta
   uso:         cómo se aplica
   tags:        hasta 3 datos cortos, ej. ["pH neutro", "Dil. 1:200"]
   destacado:   true para que salga grande
   envase:      dibujo del producto si no hay foto:
                gatillo | botella | bidon | pote | gotero | aerosol |
                pano | guante | cepillo | balde | pad | barra
                (si no lo ponés, se elige solo según el nombre)
   foto:        "fotos/mi-producto.jpg" reemplaza al dibujo

   También podés cargar todo desde la página: abajo de todo,
   botón "Cargar productos". Ahí se descarga este archivo listo.
   ========================================================= */
const PRODUCTOS = [
  // ---------- LAVADO ----------
  { nombre: "Shampoo Neutro pH7", categoria: "lavado", precio: 13900, tamano: "1 L", envase: "botella", destacado: true,
    descripcion: "Shampoo de alta lubricación que no se lleva puesta la cera ni el sellador. Mucha espuma y enjuague fácil.",
    uso: "Diluí 1 tapa cada 5 L de agua. Lavá de arriba hacia abajo con guante de microfibra y enjuagá a la sombra.",
    tags: ["pH neutro", "Dil. 1:200", "No saca cera"] },
  { nombre: "Snow Foam Rosa", categoria: "lavado", precio: 16500, tamano: "1 L", envase: "botella", destacado: true,
    descripcion: "Espuma activa bien densa para el prelavado. Ablanda la mugre antes de tocar la pintura y evita rayones.",
    uso: "Cargá el foam lance 1:10, cubrí el auto seco, dejá actuar 5 minutos sin que se seque y enjuagá a presión.",
    tags: ["Prelavado", "Dil. 1:10", "Foam lance"] },
  { nombre: "Shampoo con Cera", categoria: "lavado", precio: 15200, tamano: "1 L", envase: "botella",
    descripcion: "Lava y deja una capa fina de brillo y repelencia en un solo paso. Ideal para el lavado semanal.",
    uso: "Diluí 1:150 en el balde. Lavá, enjuagá y secá con microfibra.",
    tags: ["2 en 1", "Dil. 1:150"] },
  { nombre: "Shampoo Neutro pH7 Bidón", categoria: "lavado", precio: 52900, tamano: "5 L", envase: "bidon",
    descripcion: "El mismo shampoo neutro en formato lavadero. Rinde más de 200 lavados.",
    uso: "Diluí 1:200. Apto balde, foam lance y máquinas de lavado.",
    tags: ["Uso profesional", "Rinde 200 lavados"] },
  { nombre: "Lavado en Seco Waterless", categoria: "lavado", precio: 11800, tamano: "500 ml", envase: "gatillo",
    descripcion: "Limpia y abrillanta sin una gota de agua. Encapsula el polvo para retirarlo sin rayar.",
    uso: "Rociá por paño, pasá una microfibra en una sola dirección y repasá con otra seca.",
    tags: ["Sin agua", "Listo para usar"] },
  { nombre: "Prelavado Cítrico", categoria: "lavado", precio: 14300, tamano: "1 L", envase: "gatillo",
    descripcion: "Desprende insectos, grasa de ruta y film de tránsito de paragolpes y zócalos.",
    uso: "Rociá sobre la zona fría, dejá actuar 2 a 3 minutos y enjuagá a presión antes del lavado.",
    tags: ["Insectos", "Dil. 1:5"] },
  { nombre: "Shampoo Cerámico SiO2", categoria: "lavado", precio: 19900, tamano: "500 ml", envase: "botella",
    descripcion: "Shampoo con sílice que refuerza tratamientos cerámicos y devuelve el efecto perlado del agua.",
    uso: "Diluí 1:300. Lavá, enjuagá y secá. Usalo cada 3 o 4 lavados.",
    tags: ["SiO2", "Mantiene coatings"] },

  // ---------- DESCONTAMINADO ----------
  { nombre: "Iron Remover Descontaminante Férrico", categoria: "descontaminado", precio: 21500, tamano: "500 ml", envase: "gatillo", destacado: true,
    descripcion: "Reacciona con el polvillo de hierro incrustado y se pone violeta mientras lo disuelve. Apto pintura y llantas.",
    uso: "Sobre el auto lavado y frío, rociá, esperá 3 a 5 minutos a que cambie de color y enjuagá bien.",
    tags: ["Cambia de color", "pH neutro"] },
  { nombre: "Clay Bar Media", categoria: "descontaminado", precio: 12400, tamano: "100 g", envase: "barra",
    descripcion: "Barra de arcilla que arranca lo que el lavado no saca: brea, savia, overspray. Deja la pintura lisa como vidrio.",
    uso: "Lubricá la zona, deslizá la barra sin presión y amasala cuando se ensucie.",
    tags: ["Grado medio", "Rinde 8 autos"] },
  { nombre: "Removedor de Brea y Adhesivos", categoria: "descontaminado", precio: 13700, tamano: "500 ml", envase: "gatillo",
    descripcion: "Disuelve brea, alquitrán y restos de pegamento de calcos sin dañar la laca.",
    uso: "Rociá, esperá 1 minuto, retirá con microfibra y lavá la zona.",
    tags: ["Base solvente", "Seguro en laca"] },
  { nombre: "Lubricante para Clay", categoria: "descontaminado", precio: 8900, tamano: "500 ml", envase: "gatillo",
    descripcion: "Lubricación extra para que la barra o el guante clay deslicen sin marcar.",
    uso: "Rociá generosamente por sectores de 40 × 40 cm antes de pasar la clay.",
    tags: ["Listo para usar"] },
  { nombre: "Guante Clay Descontaminante", categoria: "descontaminado", precio: 24800, tamano: "1 u", envase: "guante",
    descripcion: "La descontaminación de la clay bar en formato guante: más rápido y si se cae, se enjuaga y sigue.",
    uso: "Usalo con shampoo o lubricante, con pasadas rectas y sin presión.",
    tags: ["Reutilizable", "Rinde 30 autos"] },

  // ---------- PULIDO ----------
  { nombre: "Compuesto de Corte Pesado", categoria: "pulido", precio: 18900, tamano: "250 ml", envase: "botella",
    descripcion: "Elimina rayas profundas, marcas de lija 1500 y oxidación. Corte alto con poco polvillo.",
    uso: "4 gotas en pad de corte o lana. Trabajá sectores de 50 × 50 cm a velocidad media.",
    tags: ["Corte 9/10", "Paso 1"] },
  { nombre: "Pulidor One Step", categoria: "pulido", precio: 19800, tamano: "250 ml", envase: "botella", destacado: true,
    descripcion: "Corrige swirls y deja brillo en una sola pasada. El favorito para autos de uso diario.",
    uso: "4 gotas en pad medio. Pasadas cruzadas hasta que el producto se vuelva transparente.",
    tags: ["Corte 6/10", "Brillo 8/10"] },
  { nombre: "Lustre Final Abrillantador", categoria: "pulido", precio: 20500, tamano: "250 ml", envase: "botella",
    descripcion: "Micro abrasivos para el último paso: saca hologramas y lleva el brillo al máximo.",
    uso: "3 gotas en pad de terminación a baja velocidad. Retirá con microfibra suave.",
    tags: ["Brillo 10/10", "Paso final"] },
  { nombre: "Pad de Espuma Corte 5\"", categoria: "pulido", precio: 9800, tamano: "1 u", envase: "pad",
    descripcion: "Espuma firme de celda abierta para compuestos de corte. Disipa temperatura y dura más.",
    uso: "Para roto orbital o rotativa con plato de 5 pulgadas.",
    tags: ["5 pulgadas", "Espuma firme"] },
  { nombre: "Pad de Espuma Finish 5\"", categoria: "pulido", precio: 9800, tamano: "1 u", envase: "pad", color: "#45d4ff",
    descripcion: "Espuma ultra blanda para lustre final y aplicación de selladores.",
    uso: "Usalo a baja velocidad y lavalo con agua tibia después de cada uso.",
    tags: ["5 pulgadas", "Espuma blanda"] },
  { nombre: "Pad de Lana 5\"", categoria: "pulido", precio: 14200, tamano: "1 u", envase: "pad", color: "#efe6cf",
    descripcion: "Lana natural trenzada para el máximo poder de corte en lacas duras.",
    uso: "Con compuesto de corte pesado. Limpiá las fibras con aire entre pasadas.",
    tags: ["Corte máximo", "Lana natural"] },

  // ---------- PROTECCIÓN ----------
  { nombre: "Cera Carnauba en Pasta", categoria: "proteccion", precio: 27900, tamano: "200 g", envase: "pote", destacado: true,
    descripcion: "Carnauba grado 1 brasileña. Brillo cálido y profundo con efecto mojado, sobre todo en colores oscuros.",
    uso: "Capa finita con aplicador, esperá 10 minutos y lustrá con microfibra.",
    tags: ["Dura 3 meses", "Efecto mojado"] },
  { nombre: "Sellador Sintético", categoria: "proteccion", precio: 23400, tamano: "250 ml", envase: "botella",
    descripcion: "Protección polimérica contra UV, lluvia ácida y lavados. Deja la pintura resbaladiza.",
    uso: "Aplicá a mano o con pad blando, dejá curar 15 minutos y retirá.",
    tags: ["Dura 6 meses", "Protección UV"] },
  { nombre: "Coating Cerámico 9H", categoria: "proteccion", precio: 68900, tamano: "50 ml", envase: "gotero", destacado: true,
    descripcion: "Recubrimiento cerámico de alta dureza. Brillo espejo, hidrofobia extrema y resistencia química.",
    uso: "Sobre pintura pulida y desengrasada. Aplicá en cruz con el taco, nivelá al minuto con microfibra.",
    tags: ["Dura 2 años", "Dureza 9H", "Alcanza 1 auto"] },
  { nombre: "Quick Detailer", categoria: "proteccion", precio: 11200, tamano: "500 ml", envase: "gatillo",
    descripcion: "Repaso rápido entre lavados: saca polvo y huellas y levanta el brillo en un minuto.",
    uso: "Rociá, pasá microfibra y lustrá con el lado seco.",
    tags: ["Uso diario", "Listo para usar"] },
  { nombre: "Cera Líquida Express", categoria: "proteccion", precio: 12900, tamano: "500 ml", envase: "gatillo",
    descripcion: "Cera en spray que se aplica sobre el auto mojado mientras lo secás.",
    uso: "2 disparos por paño después del enjuague y secá normalmente.",
    tags: ["Dura 4 semanas", "Sobre mojado"] },
  { nombre: "Sellador Spray SiO2", categoria: "proteccion", precio: 22700, tamano: "500 ml", envase: "gatillo",
    descripcion: "Sellador cerámico en spray. Efecto perlado fuerte y aplicación en 10 minutos.",
    uso: "Rociá en microfibra, distribuí y retirá con un segundo paño.",
    tags: ["Dura 4 meses", "SiO2"] },
  { nombre: "Restaurador de Plásticos Exteriores", categoria: "proteccion", precio: 14800, tamano: "250 ml", envase: "botella",
    descripcion: "Devuelve el negro a paragolpes, molduras y pasarruedas quemados por el sol.",
    uso: "Con aplicador de espuma sobre el plástico limpio y seco. Retirá el exceso.",
    tags: ["Dura 6 meses", "No engrasa"] },
  { nombre: "Sellador de Ópticas UV", categoria: "proteccion", precio: 16300, tamano: "100 ml", envase: "gotero",
    descripcion: "Capa protectora para ópticas recién pulidas. Evita que vuelvan a amarillear.",
    uso: "Aplicá una capa pareja con el paño incluido y dejá curar 12 horas sin mojar.",
    tags: ["Filtro UV", "Alcanza 6 ópticas"] },

  // ---------- LLANTAS Y CUBIERTAS ----------
  { nombre: "Limpia Llantas pH Neutro", categoria: "llantas", precio: 15600, tamano: "500 ml", envase: "gatillo", destacado: true,
    descripcion: "Disuelve polvo de freno y grasa sin ácidos. Seguro en llantas pulidas, diamantadas y pintadas.",
    uso: "Rociá con la llanta fría, cepillá, dejá actuar 3 minutos y enjuagá.",
    tags: ["Sin ácido", "Polvo de freno"] },
  { nombre: "Limpia Llantas Bidón", categoria: "llantas", precio: 58400, tamano: "5 L", envase: "bidon",
    descripcion: "Formato lavadero del limpia llantas neutro. Se puede diluir para mantenimiento.",
    uso: "Puro para llantas muy sucias, 1:3 para lavado semanal.",
    tags: ["Uso profesional", "Dil. hasta 1:3"] },
  { nombre: "Acondicionador de Cubiertas Brillo Húmedo", categoria: "llantas", precio: 10900, tamano: "500 ml", envase: "gatillo",
    descripcion: "Negro profundo y brillante que no salpica la carrocería al rodar.",
    uso: "Rociá sobre la cubierta limpia y seca. Para brillo satinado, repasá con aplicador.",
    tags: ["No salpica", "Base agua"] },
  { nombre: "Gel para Cubiertas Satinado", categoria: "llantas", precio: 12300, tamano: "400 g", envase: "pote",
    descripcion: "Gel espeso de terminación satinada tipo cubierta nueva. Aguanta varias lluvias.",
    uso: "Poca cantidad con aplicador curvo. Dejá secar 10 minutos.",
    tags: ["Acabado satinado", "Dura 3 semanas"] },
  { nombre: "Cepillo para Llantas Cerdas Suaves", categoria: "llantas", precio: 13500, tamano: "1 u", envase: "cepillo",
    descripcion: "Cerdas largas que llegan al fondo del rayo sin marcar la laca de la llanta.",
    uso: "Mojalo, cepillá con el limpiador aplicado y enjuagá el cepillo al terminar.",
    tags: ["No raya", "Mango antideslizante"] },
  { nombre: "Limpiador de Pasarruedas", categoria: "llantas", precio: 12100, tamano: "1 L", envase: "gatillo",
    descripcion: "Desengrasante fuerte para barro, grasa y brea acumulados en los pasarruedas.",
    uso: "Rociá, cepillá con cepillo duro y enjuagá a presión.",
    tags: ["Dil. 1:4", "Alto poder"] },

  // ---------- VIDRIOS ----------
  { nombre: "Limpiavidrios Sin Amoníaco", categoria: "vidrios", precio: 7900, tamano: "500 ml", envase: "gatillo",
    descripcion: "Limpia sin dejar vetas y es apto para polarizados porque no tiene amoníaco.",
    uso: "Rociá en la microfibra, limpiá en cruz y repasá con paño seco.",
    tags: ["Apto polarizado", "Sin vetas"] },
  { nombre: "Repelente de Lluvia", categoria: "vidrios", precio: 14900, tamano: "120 ml", envase: "gotero", destacado: true,
    descripcion: "A partir de 60 km/h el agua se va sola del parabrisas. Mejor visibilidad y menos uso de escobillas.",
    uso: "Sobre vidrio limpio y seco, aplicá en círculos, esperá el velo y retirá.",
    tags: ["Dura 3 meses", "Desde 60 km/h"] },
  { nombre: "Pulidor de Vidrios Quita Sarro", categoria: "vidrios", precio: 15800, tamano: "250 ml", envase: "botella",
    descripcion: "Saca las marcas de agua dura y el sarro que el limpiavidrios no puede.",
    uso: "A mano con aplicador o con pad de fieltro. Enjuagá bien al terminar.",
    tags: ["Marcas de agua", "A mano o máquina"] },
  { nombre: "Antiempañante Interior", categoria: "vidrios", precio: 9400, tamano: "250 ml", envase: "gatillo",
    descripcion: "Evita que el parabrisas se empañe por dentro en días fríos y húmedos.",
    uso: "Aplicá del lado interior con microfibra y dejá secar sin repasar de más.",
    tags: ["Dura 4 semanas", "Invierno"] },

  // ---------- INTERIOR ----------
  { nombre: "APC Multipropósito", categoria: "interior", precio: 11900, tamano: "1 L", envase: "gatillo", destacado: true,
    descripcion: "El limpiador comodín: plásticos, tapizados, alfombras, burletes y marcos de puerta.",
    uso: "Diluí según la suciedad (1:10 interior, 1:4 motor), cepillá y retirá con microfibra húmeda.",
    tags: ["Dil. 1:4 a 1:20", "Multiuso"] },
  { nombre: "Limpia Tapizados Espuma Activa", categoria: "interior", precio: 10800, tamano: "500 ml", envase: "aerosol",
    descripcion: "Espuma seca que levanta manchas de butacas, techos y alfombras sin empapar.",
    uso: "Agitá, aplicá, cepillá suave y retirá con microfibra. Dejá ventilar.",
    tags: ["Espuma seca", "Tela y alfombra"] },
  { nombre: "Limpiador de Cuero", categoria: "interior", precio: 13200, tamano: "250 ml", envase: "gatillo",
    descripcion: "Saca el brillo grasoso y la mugre del cuero sin resecarlo ni decolorarlo.",
    uso: "Rociá en cepillo de cerda suave, trabajá en círculos y retirá con microfibra.",
    tags: ["pH balanceado", "Cuero y ecocuero"] },
  { nombre: "Acondicionador de Cuero", categoria: "interior", precio: 15900, tamano: "250 ml", envase: "botella",
    descripcion: "Hidrata y protege del sol con terminación mate original. Sin olor fuerte.",
    uso: "Después de limpiar, aplicá con aplicador de microfibra y dejá absorber 15 minutos.",
    tags: ["Acabado mate", "Filtro UV"] },
  { nombre: "Acondicionador de Plásticos Mate", categoria: "interior", precio: 10400, tamano: "500 ml", envase: "gatillo",
    descripcion: "Renueva torpedo y paneles con terminación seca, sin brillo ni reflejos en el parabrisas.",
    uso: "Rociá en el aplicador, distribuí y repasá con microfibra seca.",
    tags: ["No engrasa", "Antiestático"] },
  { nombre: "Aromatizante Auto Nuevo", categoria: "interior", precio: 6900, tamano: "250 ml", envase: "gatillo",
    descripcion: "Fragancia a auto recién salido de la concesionaria. Suave y duradera.",
    uso: "2 disparos sobre alfombras. No aplicar sobre cuero ni pantallas.",
    tags: ["Dura 7 días", "No mancha"] },
  { nombre: "Eliminador de Olores", categoria: "interior", precio: 9800, tamano: "300 ml", envase: "aerosol",
    descripcion: "Neutraliza olor a cigarrillo, humedad y mascotas en vez de taparlo.",
    uso: "Con el aire en recirculación, descargá dentro del auto cerrado y ventilá a los 15 minutos.",
    tags: ["Neutraliza", "Descarga total"] },

  // ---------- MOTOR ----------
  { nombre: "Desengrasante de Motor", categoria: "motor", precio: 12600, tamano: "1 L", envase: "gatillo",
    descripcion: "Corta grasa y aceite quemado sin atacar mangueras, plásticos ni aluminio.",
    uso: "Con el motor tibio, cubrí lo eléctrico, rociá, cepillá y enjuagá con poca presión.",
    tags: ["Dil. 1:3", "Seguro en aluminio"] },
  { nombre: "Acondicionador de Motor", categoria: "motor", precio: 11700, tamano: "500 ml", envase: "gatillo",
    descripcion: "Deja plásticos y mangueras del vano con negro uniforme y los protege del calor.",
    uso: "Sobre el motor limpio y húmedo, rociá y dejá secar con el capot abierto.",
    tags: ["Base agua", "No pegajoso"] },
  { nombre: "Desengrasante Concentrado Bidón", categoria: "motor", precio: 44900, tamano: "5 L", envase: "bidon",
    descripcion: "Desengrasante alcalino concentrado para taller, lavadero y chasis.",
    uso: "Diluí de 1:5 a 1:20 según la suciedad. Usá guantes.",
    tags: ["Uso profesional", "Dil. hasta 1:20"] },

  // ---------- ACCESORIOS ----------
  { nombre: "Microfibra de Secado 1200 GSM", categoria: "accesorios", precio: 21900, tamano: "60 × 90 cm", envase: "pano", destacado: true,
    descripcion: "Seca un auto mediano de una pasada. Doble felpa, sin bordes que rayen.",
    uso: "Apoyala y arrastrala sin presión. Lavala sin suavizante.",
    tags: ["1200 GSM", "Sin bordes"] },
  { nombre: "Pack 3 Microfibras 350 GSM", categoria: "accesorios", precio: 9900, tamano: "40 × 40 cm", envase: "pano", color: "#45d4ff",
    descripcion: "Paños todo terreno para retirar ceras, limpiar interiores y vidrios.",
    uso: "Usá un color por tarea para no cruzar productos.",
    tags: ["Pack x3", "350 GSM"] },
  { nombre: "Guante de Lavado Microfibra", categoria: "accesorios", precio: 8700, tamano: "1 u", envase: "guante",
    descripcion: "Guante tipo chenille que carga mucho shampoo y atrapa la suciedad lejos de la pintura.",
    uso: "Enjuagalo en el balde limpio después de cada paño del auto.",
    tags: ["No raya", "Lavable"] },
  { nombre: "Balde con Rejilla 20 L", categoria: "accesorios", precio: 26500, tamano: "20 L", envase: "balde", color: "#ff5a1f",
    descripcion: "Balde reforzado con rejilla en el fondo que retiene la arenilla para que no vuelva al guante.",
    uso: "Usá dos: uno con shampoo y otro con agua limpia para enjuagar el guante.",
    tags: ["Rejilla incluida", "Método 2 baldes"] },
];
